# Generated by Django 2.2.3 on 2019-07-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servayapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_name',
            new_name='topic_name',
        ),
    ]
