# Generated by Django 2.2.3 on 2019-07-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pics',
        ),
    ]
